version: "3"
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: carloskono/devsre_app
    container_name: app
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PASSWORD: devsre
    volumes:
      - ./:/var/www
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
  webserver:
    build:
      context: ./
      dockerfile: .docker/DockerfileNginx
    image: carloskono/devsre_nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app

  db:
    image: mysql:5.7.32
    container_name: db
    environment:
      MYSQL_DATABASE: devsre
      MYSQL_ROOT_PASSWORD: devsre
    volumes: 
      - dbdata:/var/lib/mysql   

  composer_installation:
    container_name: composer_installation
    image: composer
    volumes:
      - ./:/var/www
    command: composer install --ignore-platform-reqs 

volumes: 
  dbdata:
    driver: local